quarkus.swagger-ui.path=/swagger-ui
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.info-title=Feedback Collector API
quarkus.smallrye-openapi.info-version=1.0.0
