name: Deploy Pipeline
on:
  push:
    branches: [ feature/migracao_aws_lambda ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build SAM
        run: sam build
      - name: Deploy SAM
        run: |
          sam deploy --no-confirm-changeset \
            --stack-name feedback-platform \
            --parameter-overrides StageName=dev \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --region us-east-2